### ISSUE TITLE
navigating issue

### ISSUE THREAD

**Issue by kingstonwilliam** [fssa-batch3/sasikumar.saminathan__web_project#8]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMmQ1NzQ2MTEtNTY3OC00Yjc3LWIyZTctN2ViM2JiNmUyNTUxIiwiZGVwbG95X2lkIjoiNjQ1MzcwMjUwMzA2YjIwMDA4NTQzNWNmIiwiaWQiOiIzNmRhM2FkZS1lZDBkLTRjOTUtYTNhZS1iZTZiM2QwNmU5NjEifQ==)

### Description of issue

I cant enter into product details.
### Expected result
its should redirect if I touch the product

### Actual result
I touch the product, but it didn't navigate to product details

### Steps to reproduce
1. I entered the home page.
2. I click the apple phone product.
3. it does not redirect to the product detail page.

```
Path:      /index.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--shopz-now.netlify.app%2Findex.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--shopz-now.netlify.app/index.html)

**Comment by Sasikumar77** [comment]
I fixed this bug : now you can click mobile container it will redirect to mobile info page.

**Comment by kingstonwilliam** [comment]
ok i checked the feature it's working fine now i'm closeing the issue.
thank you.
