### ISSUE TITLE
payment detail issue

### ISSUE THREAD

**Issue by kingstonwilliam** [fssa-batch3/sasikumar.saminathan__web_project#9]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMmQ1NzQ2MTEtNTY3OC00Yjc3LWIyZTctN2ViM2JiNmUyNTUxIiwiZGVwbG95X2lkIjoiNjQ1MzcwMjUwMzA2YjIwMDA4NTQzNWNmIiwiaWQiOiJkZTc2Mzc1Ni1kMzM1LTQ4YmEtOTkxZi05MDZjOTYxZjVmNWIifQ==)

### Description of issue
no payment detail for buying product.

### Expected result
by clicking the payment option that should be redirect to the payment detail.

### Actual result

it is showing as order confirm.
### Steps to reproduce
1. enter the product 
2. click the buy now product
3. it will show to the payment option.
4.payment details are not showed in the payment option.

```
Path:      /pages/buyer/payment.html?id=91
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--shopz-now.netlify.app%2Fpages%2Fbuyer%2Fpayment.html%3Fid%3D91&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--shopz-now.netlify.app/pages/buyer/payment.html?id=91)

**Comment by Sasikumar77** [comment]
I fixed this bug now you can see input fields with validation to enter payment details

**Comment by kingstonwilliam** [comment]
ok i will check it again and i will  close the issue.
thank you.
